### ISSUE TITLE
Got "module does not exist" exception when run spring-boot app with modulith via `java -jar app.jar`

### ISSUE THREAD

**Issue by ajax-semenov-y** [spring-projects/spring-modulith#221]
Hello! I'm currently in the process of adding Modulith to my application. At the moment, I've defined modules and created a test to verify dependencies. Everything seems to be working fine locally. However, when I attempt to start the service using `java -jar app.jar` (inside a docker container, but it does not actually matter), I'm encountering an error message: "java.lang.IllegalArgumentException: Module mymodule does not exist!"

I've created a simple project with reproduce: 
https://github.com/ajax-semenov-y/spring-modulith-issue

This demo project has 3 modules:
- module1 (declared as a shared module)
- module2 (depends on module1)
- module3 (depends on module1 and module2)

Case 1
Run `./gradlew test`
Result: test ApplicationArchUnitTest that verifies modules passed

Case 2
Run `./gradlew bootRun`
Result: service starts

Case 3
Run `./gradlew assemble && java -jar build/libs/demo-0.0.1-SNAPSHOT.jar`
Expected result: service starts (as in case 2)
Actual result: service does not start with the following exception:

```java
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Module module1 does not exist!
    at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration.lambda$toSupplier$3(SpringModulithRuntimeAutoConfiguration.java:167) ~[spring-modulith-runtime-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.modulith.runtime.ApplicationModulesRuntime.get(ApplicationModulesRuntime.java:56) ~[spring-modulith-runtime-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration.lambda$applicationModuleInitializingListener$2(SpringModulithRuntimeAutoConfiguration.java:80) ~[spring-modulith-runtime-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-6.0.10.jar!/:6.0.10]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-6.0.10.jar!/:6.0.10]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.10.jar!/:6.0.10]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437) ~[spring-context-6.0.10.jar!/:6.0.10]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.10.jar!/:6.0.10]
    at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.1.jar!/:3.1.1]
    at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:15) ~[classes!/:0.0.1-SNAPSHOT]
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
    Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Module module1 does not exist!
    at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
    at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
    at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration.lambda$toSupplier$3(SpringModulithRuntimeAutoConfiguration.java:165) ~[spring-modulith-runtime-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    ... 23 common frames omitted
    Caused by: java.lang.IllegalArgumentException: Module module1 does not exist!
    at org.springframework.modulith.core.ApplicationModules.getRequiredModule(ApplicationModules.java:496) ~[spring-modulith-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
    at org.springframework.modulith.core.ApplicationModules.of(ApplicationModules.java:523) ~[spring-modulith-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.modulith.core.ApplicationModules.lambda$of$3(ApplicationModules.java:184) ~[spring-modulith-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[na:na]
    at org.springframework.modulith.core.ApplicationModules.of(ApplicationModules.java:179) ~[spring-modulith-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.modulith.core.ApplicationModules.of(ApplicationModules.java:162) ~[spring-modulith-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration$ApplicationModulesBootstrap.initializeApplicationModules(SpringModulithRuntimeAutoConfiguration.java:143) ~[spring-modulith-runtime-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration.lambda$modulesRuntime$0(SpringModulithRuntimeAutoConfiguration.java:70) ~[spring-modulith-runtime-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]
```

I believe I have found a possible reason after some debugging. It seems that when ArchUnit attempts to load classes from Jar files, it filters out all of them. When initializing the `classFileLocations` field in `com.tngtech.archunit.core.importer.FromFilePath`, I noticed that the prefix passed to the `classFilesBeneath` filter includes an exclamation mark. However, none of the potential JarEntry candidates have this mark.

<img width="810" alt="spring-modulith-issue – ClassFileSource java  Gradle: com tngtech archunit:archunit:1 0 1  2023-06-26 18-44-55" src="https://github.com/spring-projects/spring-modulith/assets/112861111/94af2c61-6081-43bb-a317-2d3172c780a2">

Can you assist me in determining if there is an issue with my setup or if it is a bug? Thanks!

**Comment by ajax-semenov-y** [comment]
Btw, when I remove the shared module, the app starts but I get a warning message.
```
ApplicationModulesBootstrap : No application modules detected!
```

**Comment by odrotbohm** [comment]
This looks like a problem in ArchUnit as it does not seem to expect a second `!/` in the URLs returned by the classloader when looking up the package to import. I have created a PR to hopefully get this fixed quickly.

**Comment by ajax-semenov-y** [comment]
Thank you for the quick fix. I am looking forward to getting this merged.

**Comment by odrotbohm** [comment]
It looks like the ArchUnit team needs a bit more time to incorporate the fix. I'll go ahead and temporarily shadow the fixed class into our own sources to be able to ship the RC1 release.

**Comment by odrotbohm** [comment]
Closing this for now. I've filed [a follow-up ticket](246) to remove the introduced workaround before the GA release.
