### ISSUE TITLE
Code 1.0.0-M1 examples give this error

### ISSUE THREAD

**Issue by nagkumar** [spring-projects/spring-modulith#223]
`spring-modulith\spring-modulith-examples\spring-modulith-example-full>mvn package
`
results in this exception.. is it valid.. if yes, can you pl. explain
```
java.lang.IllegalStateException: ¯\_(ツ)_/¯
        at example.order.EventPublicationRegistryTests$FailingAsyncTransactionalEventListener.foo(EventPublicationRegistryTests.java:67)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.modulith.events.support.CompletionRegisteringAdvisor$CompletionRegisteringMethodInterceptor.invoke(CompletionRegisteringAdvisor.java:170)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

```

**Comment by nagkumar** [comment]
Full console log for further reference

```
spring-modulith\spring-modulith-examples\spring-modulith-example-full>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< org.springframework.modulith:spring-modulith-example-full >--------------------------
[INFO] Building Spring Modulith - Examples - Full Example 1.0.0-M1
[INFO]   from pom.xml
[INFO] ----------------------------------------------------[ jar ]-----------------------------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ spring-modulith-example-full ---
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ spring-modulith-example-full ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 10 source files with javac [debug release 17] to target\classes
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ spring-modulith-example-full ---
[INFO] skip non existing resourceDirectory C:\temp\spring-modulith\spring-modulith-examples\spring-modulith-example-full\src\test\resources
[INFO] skip non existing resourceDirectory C:\temp\spring-modulith\spring-modulith-examples\spring-modulith-example-full\src\test\resources-filtered
[INFO]
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ spring-modulith-example-full ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 4 source files with javac [debug release 17] to target\test-classes
[INFO]
[INFO] --- surefire:3.0.0:test (default-test) @ spring-modulith-example-full ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running example.ApplicationIntegrationTests
2023-06-27T14:02:12.263+05:30  INFO   --- [           main] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [example.ApplicationIntegrationTests]: ApplicationIntegrationTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
2023-06-27T14:02:12.364+05:30  INFO   --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration example.Application for test class example.ApplicationIntegrationTests

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.1)

2023-06-27T14:02:12.679+05:30  INFO 9136 --- [           main] example.ApplicationIntegrationTests      : Starting ApplicationIntegrationTests using Java 19.0.2 with PID 9136 (started by nagku in C:\temp\spring-modulith\spring-modulith-examples\spring-modulith-example-full)
2023-06-27T14:02:12.679+05:30  INFO 9136 --- [           main] example.ApplicationIntegrationTests      : No active profile set, falling back to 1 default profile: "default"
2023-06-27T14:02:13.395+05:30  INFO 9136 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-06-27T14:02:13.420+05:30  INFO 9136 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 JPA repository interfaces.
2023-06-27T14:02:13.859+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-06-27T14:02:13.997+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection conn0: url=jdbc:h2:mem:a9dbd2af-3afb-4768-9e18-f12bc43a0cc8 user=SA
2023-06-27T14:02:13.999+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-06-27T14:02:14.046+05:30  INFO 9136 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-06-27T14:02:14.113+05:30  INFO 9136 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.2.5.Final
2023-06-27T14:02:14.115+05:30  INFO 9136 --- [           main] org.hibernate.cfg.Environment            : HHH000406: Using bytecode reflection optimizer
2023-06-27T14:02:14.239+05:30  INFO 9136 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-27T14:02:14.349+05:30  INFO 9136 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2023-06-27T14:02:14.536+05:30  INFO 9136 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-27T14:02:14.991+05:30  INFO 9136 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Hibernate: drop table if exists jpa_event_publication cascade
Hibernate: create table jpa_event_publication (completion_date timestamp(6) with time zone, publication_date timestamp(6) with time zone, id uuid not null, event_type varchar(255), listener_id varchar(255), serialized_event varchar(255), primary key (id))
2023-06-27T14:02:15.014+05:30  INFO 9136 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-06-27T14:02:15.182+05:30 DEBUG 9136 --- [           main] onConfiguration$AsyncPropertiesDefaulter : Defaulting async shutdown to await termination in 2 seconds.
2023-06-27T14:02:15.209+05:30  WARN 9136 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2023-06-27T14:02:15.560+05:30  WARN 9136 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'application-modules' contains invalid characters, please migrate to a valid format.
2023-06-27T14:02:15.587+05:30 DEBUG 9136 --- [           main] o.s.m.a.ApplicationModulesEndpoint       : Activating Spring Modulith actuator.
2023-06-27T14:02:15.586+05:30 DEBUG 9136 --- [cTaskExecutor-1] onfiguration$ApplicationModulesBootstrap : Obtaining Spring Modulith application modules…
2023-06-27T14:02:15.606+05:30  INFO 9136 --- [cTaskExecutor-1] com.tngtech.archunit.core.PluginLoader   : Detected Java version 19.0.2
2023-06-27T14:02:16.445+05:30 DEBUG 9136 --- [cTaskExecutor-1] onfiguration$ApplicationModulesBootstrap : Detected 2 application modules: [order, inventory]
2023-06-27T14:02:16.667+05:30  INFO 9136 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2023-06-27T14:02:16.718+05:30 DEBUG 9136 --- [           main] .s.PersistentApplicationEventMulticaster : Looking up previously pending event publications…
Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.completion_date is null order by j1_0.publication_date
2023-06-27T14:02:17.019+05:30 DEBUG 9136 --- [           main] .s.PersistentApplicationEventMulticaster : None found.
2023-06-27T14:02:17.033+05:30  INFO 9136 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2023-06-27T14:02:17.039+05:30  INFO 9136 --- [           main] example.ApplicationIntegrationTests      : Started ApplicationIntegrationTests in 4.561 seconds (process running for 5.471)
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2023-06-27T14:02:17.603+05:30 DEBUG 9136 --- [           main] o.s.m.e.DefaultEventPublicationRegistry  : Registering publication of example.order.OrderCompleted for example.inventory.InventoryManagement.on(example.order.OrderCompleted).
Hibernate: insert into jpa_event_publication (completion_date,event_type,listener_id,publication_date,serialized_event,id) values (?,?,?,?,?,?)
2023-06-27T14:02:17.663+05:30  INFO 9136 --- [         task-1] example.inventory.InventoryManagement    : Received order completion for OrderIdentifier[id=edeb519c-7964-432a-bd00-c07b4a301fb8].
2023-06-27T14:02:18.675+05:30  INFO 9136 --- [         task-1] example.inventory.InventoryManagement    : Finished order completion for OrderIdentifier[id=edeb519c-7964-432a-bd00-c07b4a301fb8].
Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.serialized_event=? and j1_0.listener_id=? and j1_0.completion_date is null
2023-06-27T14:02:18.771+05:30 DEBUG 9136 --- [         task-1] o.s.m.e.DefaultEventPublicationRegistry  : Marking publication of event example.order.OrderCompleted to listener example.inventory.InventoryManagement.on(example.order.OrderCompleted) completed.
Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.serialized_event=? and j1_0.listener_id=? and j1_0.completion_date is null
Hibernate: update jpa_event_publication set completion_date=?,event_type=?,listener_id=?,publication_date=?,serialized_event=? where id=?
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.665 s - in example.ApplicationIntegrationTests
[INFO] Running example.ModularityTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.428 s - in example.ModularityTests
[INFO] Running example.order.EventPublicationRegistryTests
2023-06-27T14:02:20.146+05:30  INFO 9136 --- [           main] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [example.order.EventPublicationRegistryTests]: EventPublicationRegistryTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
2023-06-27T14:02:20.161+05:30  INFO 9136 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration example.Application for test class example.order.EventPublicationRegistryTests

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.1)

2023-06-27T14:02:20.188+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : Bootstrapping @org.springframework.modulith.test.ApplicationModuleTest for Order in mode STANDALONE (class example.Application)…
2023-06-27T14:02:20.188+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : # Order
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Logical name: order
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Base package: example.order
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Direct module dependencies: none
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Spring beans:
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :   + ….OrderManagement
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :   o ….internal.OrderInternal
2023-06-27T14:02:20.190+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :
2023-06-27T14:02:20.192+05:30  INFO 9136 --- [           main] e.order.EventPublicationRegistryTests    : Starting EventPublicationRegistryTests using Java 19.0.2 with PID 9136 (started by nagku in C:\temp\spring-modulith\spring-modulith-examples\spring-modulith-example-full)
2023-06-27T14:02:20.193+05:30  INFO 9136 --- [           main] e.order.EventPublicationRegistryTests    : No active profile set, falling back to 1 default profile: "default"
2023-06-27T14:02:20.331+05:30  INFO 9136 --- [           main] figurationAndEntityScanPackageCustomizer : Re-configuring auto-configuration and entity scan packages to: example.order.
2023-06-27T14:02:20.362+05:30  INFO 9136 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-06-27T14:02:20.366+05:30  INFO 9136 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 3 ms. Found 0 JPA repository interfaces.
2023-06-27T14:02:20.417+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Starting...
2023-06-27T14:02:20.420+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Added connection conn10: url=jdbc:h2:mem:e4f70d4c-c6be-4c6e-9dad-d941b5d8a572 user=SA
2023-06-27T14:02:20.420+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Start completed.
2023-06-27T14:02:20.422+05:30  INFO 9136 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-06-27T14:02:20.427+05:30  INFO 9136 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-27T14:02:20.427+05:30  INFO 9136 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2023-06-27T14:02:20.435+05:30  INFO 9136 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-27T14:02:20.452+05:30  INFO 9136 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Hibernate: drop table if exists jpa_event_publication cascade
Hibernate: create table jpa_event_publication (completion_date timestamp(6) with time zone, publication_date timestamp(6) with time zone, id uuid not null, event_type varchar(255), listener_id varchar(255), serialized_event varchar(255), primary key (id))
2023-06-27T14:02:20.454+05:30  INFO 9136 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-06-27T14:02:20.476+05:30 DEBUG 9136 --- [           main] onConfiguration$AsyncPropertiesDefaulter : Defaulting async shutdown to await termination in 2 seconds.
2023-06-27T14:02:20.540+05:30 DEBUG 9136 --- [           main] o.s.m.a.ApplicationModulesEndpoint       : Activating Spring Modulith actuator.
2023-06-27T14:02:20.540+05:30 DEBUG 9136 --- [cTaskExecutor-1] onfiguration$ApplicationModulesBootstrap : Obtaining Spring Modulith application modules…
2023-06-27T14:02:20.541+05:30 DEBUG 9136 --- [cTaskExecutor-1] onfiguration$ApplicationModulesBootstrap : Detected 2 application modules: [order, inventory]
2023-06-27T14:02:20.568+05:30 DEBUG 9136 --- [           main] .s.PersistentApplicationEventMulticaster : Looking up previously pending event publications…
Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.completion_date is null order by j1_0.publication_date
2023-06-27T14:02:20.573+05:30 DEBUG 9136 --- [           main] .s.PersistentApplicationEventMulticaster : None found.
2023-06-27T14:02:20.578+05:30  INFO 9136 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2023-06-27T14:02:20.579+05:30  INFO 9136 --- [           main] e.order.EventPublicationRegistryTests    : Started EventPublicationRegistryTests in 0.415 seconds (process running for 9.012)
2023-06-27T14:02:20.596+05:30 DEBUG 9136 --- [           main] o.s.m.e.DefaultEventPublicationRegistry  : Registering publication of example.order.OrderCompleted for example.order.EventPublicationRegistryTests$FailingAsyncTransactionalEventListener.foo(example.order.OrderCompleted).
Hibernate: insert into jpa_event_publication (completion_date,event_type,listener_id,publication_date,serialized_event,id) values (?,?,?,?,?,?)
2023-06-27T14:02:20.602+05:30 DEBUG 9136 --- [         task-1] r$CompletionRegisteringMethodInterceptor : Invocation of listener void example.order.EventPublicationRegistryTests$FailingAsyncTransactionalEventListener.foo(example.order.OrderCompleted) failed. Leaving event publication uncompleted.

java.lang.IllegalStateException: ¯\_(ツ)_/¯
        at example.order.EventPublicationRegistryTests$FailingAsyncTransactionalEventListener.foo(EventPublicationRegistryTests.java:67)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.modulith.events.support.CompletionRegisteringAdvisor$CompletionRegisteringMethodInterceptor.invoke(CompletionRegisteringAdvisor.java:170)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.completion_date is null order by j1_0.publication_date
Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.completion_date is null order by j1_0.publication_date
2023-06-27T14:02:20.771+05:30  INFO 9136 --- [           main] o.s.m.e.DefaultEventPublicationRegistry  : Shutting down with the following publications left unfinished:
2023-06-27T14:02:20.774+05:30  INFO 9136 --- [           main] o.s.m.e.DefaultEventPublicationRegistry  : └─ example.order.OrderCompleted - example.order.EventPublicationRegistryTests$FailingAsyncTransactionalEventListener.foo(example.order.OrderCompleted)
2023-06-27T14:02:20.781+05:30  INFO 9136 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
Hibernate: drop table if exists jpa_event_publication cascade
2023-06-27T14:02:20.785+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown initiated...
2023-06-27T14:02:20.790+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown completed.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.656 s - in example.order.EventPublicationRegistryTests
[INFO] Running example.order.OrderIntegrationTests
2023-06-27T14:02:20.798+05:30  INFO 9136 --- [           main] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [example.order.OrderIntegrationTests]: OrderIntegrationTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
2023-06-27T14:02:20.800+05:30  INFO 9136 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration example.Application for test class example.order.OrderIntegrationTests

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.1)

2023-06-27T14:02:20.832+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : Bootstrapping @org.springframework.modulith.test.ApplicationModuleTest for Order in mode STANDALONE (class example.Application)…
2023-06-27T14:02:20.832+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : # Order
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Logical name: order
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Base package: example.order
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Direct module dependencies: none
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Spring beans:
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :   + ….OrderManagement
2023-06-27T14:02:20.833+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :   o ….internal.OrderInternal
2023-06-27T14:02:20.834+05:30  INFO 9136 --- [           main] ustomizerFactory$ModuleContextCustomizer :
2023-06-27T14:02:20.836+05:30  INFO 9136 --- [           main] example.order.OrderIntegrationTests      : Starting OrderIntegrationTests using Java 19.0.2 with PID 9136 (started by nagku in C:\temp\spring-modulith\spring-modulith-examples\spring-modulith-example-full)
2023-06-27T14:02:20.837+05:30  INFO 9136 --- [           main] example.order.OrderIntegrationTests      : No active profile set, falling back to 1 default profile: "default"
2023-06-27T14:02:20.953+05:30  INFO 9136 --- [           main] figurationAndEntityScanPackageCustomizer : Re-configuring auto-configuration and entity scan packages to: example.order.
2023-06-27T14:02:20.973+05:30  INFO 9136 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-06-27T14:02:20.977+05:30  INFO 9136 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 3 ms. Found 0 JPA repository interfaces.
2023-06-27T14:02:21.026+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-3 - Starting...
2023-06-27T14:02:21.028+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-3 - Added connection conn20: url=jdbc:h2:mem:785244c7-14b3-424a-9d04-1835f1013a8d user=SA
2023-06-27T14:02:21.029+05:30  INFO 9136 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-3 - Start completed.
2023-06-27T14:02:21.030+05:30  INFO 9136 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-06-27T14:02:21.037+05:30  INFO 9136 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-27T14:02:21.038+05:30  INFO 9136 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2023-06-27T14:02:21.044+05:30  INFO 9136 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-06-27T14:02:21.057+05:30  INFO 9136 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Hibernate: drop table if exists jpa_event_publication cascade
Hibernate: create table jpa_event_publication (completion_date timestamp(6) with time zone, publication_date timestamp(6) with time zone, id uuid not null, event_type varchar(255), listener_id varchar(255), serialized_event varchar(255), primary key (id))
2023-06-27T14:02:21.059+05:30  INFO 9136 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-06-27T14:02:21.070+05:30 DEBUG 9136 --- [           main] onConfiguration$AsyncPropertiesDefaulter : Defaulting async shutdown to await termination in 2 seconds.
2023-06-27T14:02:21.133+05:30 DEBUG 9136 --- [           main] o.s.m.a.ApplicationModulesEndpoint       : Activating Spring Modulith actuator.
2023-06-27T14:02:21.133+05:30 DEBUG 9136 --- [cTaskExecutor-1] onfiguration$ApplicationModulesBootstrap : Obtaining Spring Modulith application modules…
2023-06-27T14:02:21.134+05:30 DEBUG 9136 --- [cTaskExecutor-1] onfiguration$ApplicationModulesBootstrap : Detected 2 application modules: [order, inventory]
2023-06-27T14:02:21.155+05:30 DEBUG 9136 --- [           main] .s.PersistentApplicationEventMulticaster : Looking up previously pending event publications…
Hibernate: select j1_0.id,j1_0.completion_date,j1_0.event_type,j1_0.listener_id,j1_0.publication_date,j1_0.serialized_event from jpa_event_publication j1_0 where j1_0.completion_date is null order by j1_0.publication_date
2023-06-27T14:02:21.158+05:30 DEBUG 9136 --- [           main] .s.PersistentApplicationEventMulticaster : None found.
2023-06-27T14:02:21.161+05:30  INFO 9136 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2023-06-27T14:02:21.162+05:30  INFO 9136 --- [           main] example.order.OrderIntegrationTests      : Started OrderIntegrationTests in 0.358 seconds (process running for 9.594)
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.494 s - in example.order.OrderIntegrationTests
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO]


```

**Comment by odrotbohm** [comment]
Would you mind not spamming the bug tracker with general questions? Feel free to raise those on StackOverflow tagged with `#spring-modulith`. As visible from the final test result output, there is no error on place. What you see is the log output of a test, that wants to produce the error.

**Comment by nagkumar** [comment]
>Would you mind not spamming the bug tracker with general questions? 

Sorry, I should have used `discussions`..

>StackOverflow tagged with #spring-modulith

will follow `StackOverflow  `approach as per your recommendation instead of `discussions `which I though would be more appropriate
