### ISSUE TITLE
`ModuleTracingBeanPostProcessor` potentially triggers accidental cycle on lookup of autoconfiguration packages

### ISSUE THREAD

**Issue by JanGroot** [spring-projects/spring-modulith#315]
Whenever modulith observability is on the classpath a bean as 
`
@Bean 
 fun taxMap() =
        mapOf("1" to "2")
`

fails to instantiate.

The exception:
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Illegal arguments to factory method`

`Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar:6.0.11]`

**Comment by odrotbohm** [comment]
Any chance you provide a reproducible example of this (plain Java, please)?

**Comment by odrotbohm** [comment]
No rush! 🙃

**Comment by JanGroot** [comment]
https://github.com/JanGroot/observer

Now, not the same error as in my kotlin project. but still an issue.

**Comment by odrotbohm** [comment]
Lovely, thanks. I’ll have a look ASAP.

**Comment by odrotbohm** [comment]
This should be fixed. Your example working is now running into a missing `Tracer` bean.

**Comment by JanGroot** [comment]
I've updated my project to 1.0.2-SNAPSHOT and added the Tracer.
The original error now occurs.
` Failed to instantiate [java.util.Map]: Illegal arguments to factory method 'someBean'; args: 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:157) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-6.0.12.jar:6.0.12]
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[na:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]`

**Comment by odrotbohm** [comment]
Does your sample code produce that error now?

**Comment by JanGroot** [comment]
Indeed
