### ISSUE TITLE
ApplicationModuleTest does not scope Repositories

### ISSUE THREAD

**Issue by DanieldeJongVeldstra** [spring-projects/spring-modulith#316]
While working with Spring Modulith I am trying to test the ApplicationModuleTest in a multi module application. I am running into problems when spring is trying to create JpaRepositories implementations for modules that are not under test.

My project structure is as follows:

> nl.daniel.dejong
> - Application.java
> - inventorymanagement
>   - domain
>     - ProductService.java
>     - Product.java
>     - ProductId.java
>   - infrastructure.persistence
>     - ProductJpaPersistence.java
> - orderfulfillment
>   - domain
>     - OutboundOrder.java
>   - infrastructure.persistence
>     - OutboundOrderJpaPersistence.java

The persistences are default JpaPersistences using the domain object as domain object eg:

    @Repository
    public interface ProductJpaPersistence extends ProductPersistence, JpaRepository<Product, ProductId> {
    }

My Application.java looks as follows

    @SpringBootApplication
    @EnableAsync
    @ConfigurationPropertiesScan
    @EnableJpaRepositories
    public class Application {
        public static void main(String... args) {
            SpringApplication.run(Application.class, args);
        }
    }

When creating a `ApplicationModuleTest` for the product module It is trying to create a `OutboundOrderJpaPersistence` bean. The results into the problem that the ApplicationModuleTest annotation filters the scope of the test and therefor it cannot find the OutboundOrder that the Repository is managing. 

Test:

    @ApplicationModuleTest
    @RequiredArgsConstructor
    class ProductIntegrationTest {
        private static final String PRODUCT_NAME = "Product 1";
        private final ProductService productService;
    
        @Test
        public void createProduct(Scenario scenario) {
            var createProduct = new Product();
            createProduct.setName(PRODUCT_NAME);
    
            scenario.stimulate(() -> productService.create(createProduct))
                    .andWaitForEventOfType(ProductCreated.class)
                    .matchingMappedValue(ProductCreated::name, PRODUCT_NAME);
    
        }
    }

StackTrace:

    org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [final nl.daniel.dejong.inventorymanagement.application.product.ProductService productService] in constructor [public nl.daniel.dejong.inventorymanagement.ProductIntegrationTest(nl.daniel.dejong.inventorymanagement.application.product.ProductService)]: Failed to load ApplicationContext for [WebMergedContextConfiguration@6ed000ba testClass = nl.daniel.dejong.inventorymanagement.ProductIntegrationTest, locations = [], classes = [nl.daniel.dejong.Application], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [[ImportsContextCustomizer@5862dc47 key = [org.springframework.modulith.test.ModuleTestAutoConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@446a1e84, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@626abbd0, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@37313c84, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@415b0b49, org.springframework.modulith.test.ModuleContextCustomizerFactory$ModuleContextCustomizer@17503f8a, org.springframework.boot.test.context.SpringBootTestAnnotation@ab9d71ae], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
    
    	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameter(ParameterResolutionUtils.java:159)
    	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameters(ParameterResolutionUtils.java:103)
    	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:59)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
    	at java.base/java.util.Optional.orElseGet(Optional.java:364)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
    	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$before$2(ClassBasedTestDescriptor.java:203)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:202)
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
    	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
    	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
    	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
    	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
    	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
    	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
    	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
    	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
    	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
    	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
    	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
    Caused by: java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@6ed000ba testClass = nl.daniel.dejong.inventorymanagement.ProductIntegrationTest, locations = [], classes = [nl.daniel.dejong.Application], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [[ImportsContextCustomizer@5862dc47 key = [org.springframework.modulith.test.ModuleTestAutoConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@446a1e84, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@626abbd0, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@37313c84, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@415b0b49, org.springframework.modulith.test.ModuleContextCustomizerFactory$ModuleContextCustomizer@17503f8a, org.springframework.boot.test.context.SpringBootTestAnnotation@ab9d71ae], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:143)
    	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:127)
    	at org.springframework.test.context.junit.jupiter.SpringExtension.getApplicationContext(SpringExtension.java:283)
    	at org.springframework.test.context.junit.jupiter.SpringExtension.resolveParameter(SpringExtension.java:269)
    	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameter(ParameterResolutionUtils.java:136)
    	... 51 more
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'outboundOrderJpaPersistence' defined in nl.daniel.dejong.orderfulfillment.infrastructure.persistence.OutboundOrderJpaPersistence defined in @EnableJpaRepositories declared on Application: Not a managed type: class nl.daniel.dejong.orderfulfillment.domain.order.OutboundOrder
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
    	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:967)
    	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
    	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
    	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
    	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
    	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
    	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
    	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1406)
    	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:545)
    	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
    	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:187)
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:119)
    	... 55 more
    Caused by: java.lang.IllegalArgumentException: Not a managed type: class nl.daniel.dejong.orderfulfillment.domain.order.OutboundOrder
    	at org.hibernate.metamodel.model.domain.internal.JpaMetamodelImpl.managedType(JpaMetamodelImpl.java:192)
    	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.managedType(MappingMetamodelImpl.java:467)
    	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.managedType(MappingMetamodelImpl.java:97)
    	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:82)
    	at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getEntityInformation(JpaEntityInformationSupport.java:69)
    	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getEntityInformation(JpaRepositoryFactory.java:246)
    	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:211)
    	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:194)
    	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:81)
    	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:317)
    	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
    	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
    	at org.springframework.data.util.Lazy.get(Lazy.java:114)
    	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)
    	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:132)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
    	... 76 more

When changing the `@EnableJpaRepositories` to point to the module under test `@EnableJpaRepositories("nl.daniel.dejong.inventorymanagement")` the test works as expected.

PS: The situation described above is a representation as close as possible to the full implementation, but it could miss some information. Left out some of the details to not cloud the post.

Also asked this question on stackoverflow: https://stackoverflow.com/q/77218252/3668523

**Comment by DanieldeJongVeldstra** [comment]
Some extra context here, if I remove the `@EnableJpaRepositories` from the Application.java and place the `@EnableJpaRepositories` on the test class it does work. Still wondering if the ApplicationModuleTest should scope this on its own.

**Comment by odrotbohm** [comment]
`@AMT` can't do that, as it can only interact with autoconfiguration. If you explicitly enable repository scanning for the root package, we cannot / do not interfere with that.

**Comment by odrotbohm** [comment]
Would you mind trying the latest 1.1 snapshots? We've pushed some infrastructure that actively removes beans declared in modules not part of the bootstrap from the application context. That might actually fix the problem here, too.

**Comment by DanieldeJongVeldstra** [comment]
I will have a look later today, I am curious how you view the usage of spring data in combination with spring-modulith.

**Comment by DanieldeJongVeldstra** [comment]
I have verified, and it seems to work as long as I have no `@EnableJpaRepositories` enabled on my Application.java. It might be an improvement for `spring-data-jpa` to be able to override the EnableJpaRepositories which then could be used by `@ATM` to scope the repositories correctly. (Don't know the insides if `spring-data-jpa` if that is possible to do though.

**Comment by odrotbohm** [comment]
I just tried a sample project of mine and the 1.1 snapshots actually remove the repository bean definitions triggered by `@EnableJpaRepositories` that live in modules not included in the test run. Do I get you right that you claim this is still not the case? If so, would you mind creating a small reproducer that shows the repositories residing in modules not bootstrapped being registered?

**Comment by DanieldeJongVeldstra** [comment]
The following repository should contain the reproduction, it might contain a bit of boiler plate that is not necessary but it should suffice.

https://github.com/DanieldeJongVeldstra/modulith-test-example

**Comment by odrotbohm** [comment]
I get this to work if I upgrade the project to Boot 3.2 snapshots, the version that Spring Modulith 1.1 snapshots depend on. I do not fully understand why that's solving the problem, yet, but I think I'll go ahead and mark this issue as fixed as the changes introduced in #320 definitely remove all non-bootstrap-included module bean from the bean factory.

**Comment by DanieldeJongVeldstra** [comment]
What maven repositories are u using to get the 3.2 snapshots to work, with only the snapshot repository I am not able to resolve a lot of dependencies. I would like to verify it in both my projects if possible.

**Comment by DanieldeJongVeldstra** [comment]
Verified it with 3.2.0-M3 looking forward to when the release comes
