### ISSUE TITLE
Observability proxying accidentally processes configuration classes

### ISSUE THREAD

**Issue by JanGroot** [spring-projects/spring-modulith#332]
I've updated my project to 1.0.2-SNAPSHOT and added the Tracer.
The original error now occurs.
` Failed to instantiate [java.util.Map]: Illegal arguments to factory method 'someBean'; args: 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:157) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-6.0.12.jar:6.0.12]
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[na:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]`

_Originally posted by @JanGroot in https://github.com/spring-projects/spring-modulith/issues/315#issuecomment-1764565538_

**Comment by JanGroot** [comment]
@odrotbohm  I couldnt re-open so took the liberty of opening this one.

The sample project now gives this error.
(Without the modulith-observability dependency it runs fine)

**Comment by JanGroot** [comment]
Thanks!

**Comment by odrotbohm** [comment]
We're now excluding configuration classes from observability proxying completely. Also, back ported to 1.0.x in #333.
