### ISSUE TITLE
Submodules with same name -> IllegalStateException: Duplicate key

### ISSUE THREAD

**Issue by torstenmandry** [spring-projects/spring-modulith#404]
I try to model a rather complex modulith with modules that contain submodules with identical names.

Example:

```
com.example
    .module1
        .submodule1`
    .module2
        .submodule1
```

Only the submodule packages are annotated with `ApplicationModule`.

When doing this, `ApplicationModules.of(Application.class)` throws a `java.lang.IllegalStateException: Duplicate key submodule1`.

Is there any way to override/configure, how the logical names of the ApplicationModules are derived? Looking at the sources of `ApplicationModule` I can see a boolean flag `useFullyQualifiedModuleNames` which might be what I am looking for. But currently, there seems to be no designated way to configure it.

Another option could be to use the relative package name starting from the application base package (`module1.submodule1`).

**Comment by odrotbohm** [comment]
Submodules are not supported, yet. It's gonna be a theme for 1.2 though. `useFullyQualifiedModuleNames` can be found on `@Modulithic` which needs to go on the main Spring Boot class. Still, none of the overall arrangement and verifications is currently built with sub-modules in mind, so I don't think you're gonna get much further.

**Comment by torstenmandry** [comment]
The `@Modulithic(useFullyQualifiedModuleNames = true)` annotation at the `Application` class did the trick. Now, the full name of the package is used as the logical module name, so `com.example.module1.submodule1` and `com.example.module2.submodule1` in my example.

Thanks a lot for your quick help 👍

**Comment by nilskasseckert** [comment]
Hello @torstenmandry ,
I have an error in this context. I am also getting duplicate keys. The problem is solved with the annotation `useFullyQualifiedModuleNames = true`.

However, if I now create the UML with the following code:
```
 new Documenter(modules)
        .writeModulesAsPlantUml()
```

 I get the following error:
```
java.lang.IllegalArgumentException: A component named 'XXX' already exists for this container.

	at com.structurizr.model.Model.addComponent(Model.java:267)
	at com.structurizr.model.Container.addComponent(Container.java:102)
	at org.springframework.modulith.docs.Documenter.lambda$getComponents$11(Documenter.java:466)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.Spliterators$1Adapter.forEachRemaining(Spliterators.java:706)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.springframework.modulith.docs.Documenter.getComponents(Documenter.java:465)
	at org.springframework.modulith.docs.Documenter.addComponentsToView(Documenter.java:493)
	at org.springframework.modulith.docs.Documenter.createPlantUml(Documenter.java:587)
	at org.springframework.modulith.docs.Documenter.writeModulesAsPlantUml(Documenter.java:294)
	at org.springframework.modulith.docs.Documenter.writeModulesAsPlantUml(Documenter.java:278)
	at de.netzebw.msb.mapa.bl.SpringBootModulTest.writeDocumentationSnippets(SpringBootModulTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Apparently the Fully Qualified Name is not used when drawing. Is there a workaround for this?

Regards,
Nils

**Comment by odrotbohm** [comment]
Is there any chance you provide a minimal reproducer for this? We've changed the default module name to contain everything under the application base package. In other words, in the original example given, the 1.3 versions should yield module names of `module1`, `module1.submodule1`, `module2`, and `module2.submodule1`. It would be nice if you were able to reproduce on the current 1.3 M3 or confirm it doesn't require using fully qualified module names.
