### ISSUE TITLE
Event externalisation with AMQP fails to complete 

### ISSUE THREAD

**Issue by antechrestos** [spring-projects/spring-modulith#438]
I observes traces with externalisation with AMQP

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Delegate must not return null!
	at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:78)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Delegate must not return null!
	at org.springframework.modulith.events.support.DelegatingEventExternalizer.externalize(DelegatingEventExternalizer.java:80)
	at org.springframework.modulith.events.support.EventExternalizationSupport.externalize(EventExternalizationSupport.java:87)
```

After debugging, I see that [DelegatingEventExternalizer](https://github.com/spring-projects/spring-modulith/blob/88f65f18cb1a1e2252239ddceabebd9e29a3b35e/spring-modulith-events/spring-modulith-events-core/src/main/java/org/springframework/modulith/events/support/DelegatingEventExternalizer.java#L78) does not accept its delegate to return `null`. However, [RabbitEventExternalizerConfiguration](https://github.com/spring-projects/spring-modulith/blob/88f65f18cb1a1e2252239ddceabebd9e29a3b35e/spring-modulith-events/spring-modulith-events-amqp/src/main/java/org/springframework/modulith/events/amqp/RabbitEventExternalizerConfiguration.java#L66)  instanciates one with a delegate returning `null`

Then externalization fails and remains uncomplete even if message is successfully posted.

**Comment by matiwinnetou** [comment]
I can confirm seeing the same issue and I would appreciate 1.1.2 release with this bug fix if possible.

**Comment by odrotbohm** [comment]
It'll definitely be backported. We just create separate tickets for those. Rest assured, it'll be fixed in 1.1.2.

**Comment by antechrestos** [comment]
@odrotbohm I proposed a PR for this subject

**Comment by odrotbohm** [comment]
I've seen that, thanks.

**Comment by odrotbohm** [comment]
That's fixed and backported.
