### ISSUE TITLE
Parameter biding fails for batches in `JdbcEventPublicationRepository.delete(List<UUID>)`

### ISSUE THREAD

**Issue by Fezlight** [spring-projects/spring-modulith#617]
Spring Modulith version 1.1.4

I tried to use the **CompletedEventPublications** bean, and when I use it to delete events older than a specified parameter, I encounter an error like this .

```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [DELETE
FROM EVENT_PUBLICATION
WHERE
		ID IN (?)
]; L'indice de la colonne est hors limite : 2, nombre de colonnes : 1.
```

I think this error is related to the "JdbcEventPublicationRepository#deletePublications" method who try to set two parameters instead of one.

Here is the full log output of the request
```
2024-05-22T11:23:00.022+02:00 DEBUG 66780 --- [TestEvents] [   scheduling-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [DELETE
FROM EVENT_PUBLICATION
WHERE
		ID IN (?)
]
2024-05-22T11:23:00.022+02:00 TRACE 66780 --- [TestEvents] [   scheduling-1] o.s.jdbc.core.StatementCreatorUtils      : Setting SQL statement parameter value: column index 1, parameter value [a6c0f676-9ea9-470e-bc96-cf532c99170a], value class [java.util.UUID], SQL type unknown
2024-05-22T11:23:00.022+02:00 TRACE 66780 --- [TestEvents] [   scheduling-1] o.s.jdbc.core.StatementCreatorUtils      : Setting SQL statement parameter value: column index 2, parameter value [27b8dff1-4f98-4336-b209-5496df9576c0], value class [java.util.UUID], SQL type unknown
2024-05-22T11:23:00.022+02:00 ERROR 66780 --- [TestEvents] [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [DELETE
FROM EVENT_PUBLICATION
WHERE
		ID IN (?)
]; L'indice de la colonne est hors limite : 2, nombre de colonnes : 1.
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:118) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:107) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:116) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1548) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:677) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:701) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:1047) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:1063) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:1054) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.modulith.events.jdbc.JdbcEventPublicationRepository.deletePublications(JdbcEventPublicationRepository.java:238) ~[spring-modulith-events-jdbc-1.1.4.jar:1.1.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354) ~[spring-aop-6.1.6.jar:6.1.6]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716) ~[spring-aop-6.1.6.jar:6.1.6]
	at org.springframework.modulith.events.jdbc.JdbcEventPublicationRepository$$SpringCGLIB$$0.deletePublications(<generated>) ~[spring-modulith-events-jdbc-1.1.4.jar:1.1.4]
	at org.springframework.modulith.events.core.DefaultEventPublicationRegistry.deletePublications(DefaultEventPublicationRegistry.java:149) ~[spring-modulith-events-core-1.1.4.jar:1.1.4]
	at org.springframework.modulith.events.core.DefaultEventPublicationRegistry.deletePublicationsOlderThan(DefaultEventPublicationRegistry.java:161) ~[spring-modulith-events-core-1.1.4.jar:1.1.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354) ~[spring-aop-6.1.6.jar:6.1.6]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716) ~[spring-aop-6.1.6.jar:6.1.6]
	at org.springframework.modulith.events.core.DefaultEventPublicationRegistry$$SpringCGLIB$$0.deletePublicationsOlderThan(<generated>) ~[spring-modulith-events-core-1.1.4.jar:1.1.4]
	at fr.fezlight.eventsystem.config.EventSchedulingTaskConfig.clearCompletedEvent(EventSchedulingTaskConfig.java:36) ~[spring-boot-starter-event-system-0.1.0-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.6.jar:6.1.6]
	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.5.jar:1.12.5]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96) ~[spring-context-6.1.6.jar:6.1.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.postgresql.util.PSQLException: L'indice de la colonne est hors limite : 2, nombre de colonnes : 1.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:70) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:144) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgPreparedStatement.bindBytes(PgPreparedStatement.java:1113) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgPreparedStatement.setUuid(PgPreparedStatement.java:1709) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:1011) ~[postgresql-42.7.3.jar:42.7.3]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:na]
	at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:453) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:247) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:179) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate$2.setValues(JdbcTemplate.java:1083) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$getPreparedStatementCallback$6(JdbcTemplate.java:1603) ~[spring-jdbc-6.1.6.jar:6.1.6]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658) ~[spring-jdbc-6.1.6.jar:6.1.6]
	... 39 common frames omitted
```

Why not use the deleteCompletedPublicationsOlderThan method in the CompletedEventPublications interface instead?

**Comment by odrotbohm** [comment]
Good catch! I'm setting up a separate ticket for switching `DefaultEventPublicationRegistry` to the corresponding repository. I'll fix the SQL bug against this ticket.
