### ISSUE TITLE
Strange error in docker environment

### ISSUE THREAD

**Issue by monandszy** [spring-projects/spring-modulith#686]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1501)
        at com.tngtech.archunit.core.importer.NormalizedUri.<init>(NormalizedUri.java:36)
        at com.tngtech.archunit.core.importer.NormalizedUri.from(NormalizedUri.java:79)
        at com.tngtech.archunit.core.importer.Location$FilePathLocation.from(Location.java:358)
        at com.tngtech.archunit.core.importer.Location$FilePathLocationFactory.create(Location.java:242)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:192)
        at com.tngtech.archunit.core.importer.Location.of(Location.java:184)
        at com.tngtech.archunit.core.importer.Locations.of(Locations.java:61)
        at com.tngtech.archunit.core.importer.Locations.getResourceLocations(Locations.java:128)
        at com.tngtech.archunit.core.importer.Locations.getLocationsOf(Locations.java:115)
        at com.tngtech.archunit.core.importer.Locations.ofPackage(Locations.java:75)
        at com.tngtech.archunit.core.importer.ClassFileImporter.lambda$importPackages$1(ClassFileImporter.java:212)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:213)
        at org.springframework.modulith.core.ApplicationModules.<init>(ApplicationModules.java:131)
        at org.springframework.modulith.core.ApplicationModules.<init>(ApplicationModules.java:104)
        at org.springframework.modulith.core.ApplicationModules.lambda$of$17(ApplicationModules.java:607)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.springframework.modulith.core.ApplicationModules.of(ApplicationModules.java:603)
        at org.springframework.modulith.core.ApplicationModules.of(ApplicationModules.java:223)
        at org.springframework.modulith.core.ApplicationModules.of(ApplicationModules.java:205)
        at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration$ApplicationModulesBootstrap.initializeApplicationModules(SpringModulithRuntimeAutoConfiguration.
java:157)
        at org.springframework.modulith.runtime.autoconfigure.SpringModulithRuntimeAutoConfiguration.lambda$modulesRuntime$0(SpringModulithRuntimeAutoConfiguration.java:70)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.lang.Thread.run(Thread.java:1583)

I get this error when running the application in a docker environment, when trying to access http://localhost:8080/actuator/modulith. Strangely, everything works fine, as expected, when I run the jar outside of docker.
You can check the code here (run the composeProdUp gradle task) https://github.com/monandszy/project-base/tree/feature/springModulith
You can access the container logs via: docker logs prod-backend-1

**Comment by monandszy** [comment]
Running the applicaiton as a fat jar, insted of splitting it into layers helped
