### ISSUE TITLE
Add support for MariaDB database driver

### ISSUE THREAD

**Issue by Fezlight** [spring-projects/spring-modulith#836]
Do you have any information about support for MariaDB database through it's dedicated driver "org.mariadb.jdbc:mariadb-java-client" ? 

 ```
 Caused by: java.lang.IllegalArgumentException: Unsupported database type: MariaDB
	at org.springframework.modulith.events.jdbc.DatabaseType.lambda$from$1(DatabaseType.java:54)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.springframework.modulith.events.jdbc.DatabaseType.from(DatabaseType.java:54)
	at org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration.databaseType(JdbcEventPublicationAutoConfiguration.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
	... 85 common frames omitted
```

As an alternative, because MariaDB works like MySQL we can switch to the MySQL driver if version under 11.X but we loose some specific feature added by driver itself.

**Comment by odrotbohm** [comment]
We can, of course, add support for that. If you'd like to help, do you think could duplicate the `MYSQL` enum value in `DatabaseType` and create copies of the MySQL-related tests and schema files? Given the similar nature of Maria with MySQL, I don't think any further adjustments should be necessary.

**Comment by Fezlight** [comment]
Yes, I think duplicating the value of the enum is sufficient, as both work in the same way. I can do a PR when i got some time.

**Comment by Fezlight** [comment]
I finally opened the pull request :) #839

**Comment by odrotbohm** [comment]
You apparently found time pretty quickly! 🙃 Merged, thanks!
