### ISSUE TITLE
@Externalized annotation to take values from application.yml file

### ISSUE THREAD

**Issue by Chitranshagarwal2000** [spring-projects/spring-modulith#881]
Hello,
I have a Spring Boot Application. I am using spring Modulith and I want events to be externalized to AWS SQS. Everything works fine but the `@Externalized` annotation doesn't seem to be taking values from `application.yml` file. Below is the sample code.

```
@Externalized("${aws.order-completion-queue}")
public record OrderCompletedEvent(
        String prefix,
        String companyName,
        String firstName,
        String lastName,
        String email,
        String contactNumber,
        String orderId
) {
}
```
*application.yml*
```
aws:
 order-completion-queue: order-completion-dev-queue.fifo
```

FYI - I have verified the indentation and also that the queue exists. I am using the same placeholder on `@SqsListener` in my application and that works fine.
Also hardcoding the queue name works.

Please suggest if I am doing something wrong, if not what would be the best way to use the `yml` file properties in `@Externalized` annotation

Edit 1 - This is the error that I am getting 
```
Caused by: java.util.concurrent.CompletionException: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue ${aws.order-completion-queue} with strategy CREATE and queueAttributesNames []
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152) ~[na:na]
	... 42 common frames omitted
Caused by: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue ${aws.order-completion-queue} with strategy CREATE and queueAttributesNames []
	at io.awspring.cloud.sqs.QueueAttributesResolver.wrapException(QueueAttributesResolver.java:90) ~[spring-cloud-aws-sqs-3.2.0.jar:3.2.0]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974) ~[na:na]
	... 42 common frames omitted
Caused by: software.amazon.awssdk.services.sqs.model.SqsException: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length (Service: Sqs, Status Code: 400, Request ID: eb9ee289-d753-4a3c-84b6-22cd769ffc29)
	at software.amazon.awssdk.services.sqs.model.SqsException$BuilderImpl.build(SqsException.java:104) ~[sqs-2.25.70.jar:na]
	at software.amazon.awssdk.services.sqs.model.SqsException$BuilderImpl.build(SqsException.java:58) ~[sqs-2.25.70.jar:na]
```

I am using Spring 3.3.4 and below is a snippet of my pom consisting of modulith specific dependencies

```
<dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-actuator</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-observability</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-events-aws-sqs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-jpa</artifactId>
        </dependency>
```

**Comment by odrotbohm** [comment]
The routing target declared in an annotation is currently not processed at all, but used as is. You can currently already work around this limitation by providing a programmatic routing lookup by declaring a bean of type `EventExternalizationConfiguration` using the `route(Class<T>, Function<T, RoutingTarget>)` method.

That said, we could pipe the routing target through the SpEL processing we already apply for the routing key. You'd have to use a SpEL expression such as `#{env['aws.order-completion-queue']}`. Would that be okay for you?

**Comment by Chitranshagarwal2000** [comment]
I was able to do that with `EventExternalizationConfiguration`. While I was struggling with this I did try SpEL `#{environment['aws.order-completion-queue']}`. I noticed I have to use `env` instead of `environment`, but yeah this will work for me. Will try and let you know

By the way love the work. Thanks for a great project 👍🏻

**Comment by odrotbohm** [comment]
This in place now. The latest snapshots should support SpEL expressions in the target definitions as well.
