### ISSUE TITLE
EventListener in DelegatingEventExternalizer could not be created

### ISSUE THREAD

**Issue by paulharkink** [spring-projects/spring-modulith#973]
When using Spring Modulith 1.2.5 with Spring Boot 3.3.5, the auto-configured DelegatingEventExternalizer instance 'kafkaEventExternalizer' appears to be created as a JdkProxy, which the EventListenerMethodProcessor can not find the `@ApplicationModuleListener` annotated method on, resulting in the following stacktrace:

```
org.springframework.beans.factory.BeanInitializationException: Failed to process @EventListener annotation on bean with name 'kafkaEventExternalizer': Need to invoke method 'externalize' declared on target class 'DelegatingEventExternalizer', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
	at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:150)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:986)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	...
Caused by: java.lang.IllegalStateException: Need to invoke method 'externalize' declared on target class 'DelegatingEventExternalizer', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
	at org.springframework.core.MethodIntrospector.selectInvocableMethod(MethodIntrospector.java:135)
	at org.springframework.aop.support.AopUtils.selectInvocableMethod(AopUtils.java:146)
	at org.springframework.context.event.EventListenerMethodProcessor.processBean(EventListenerMethodProcessor.java:190)
	at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:146)
```

I'll be glad to provide additional details as required!

**Comment by odrotbohm** [comment]
Can you provide a reproducer for the exception? I wonder what triggers the proxy creation for `DelegatingEventExternalizer ` in the first place.

**Comment by paulharkink** [comment]
Hi! Thanks for having a look. I was able to minimise and clean up our project so that it's just enough to reproduce the issue, please see the attached zip.
[issue973.zip](https://github.com/user-attachments/files/17991118/issue973.zip)

**Comment by odrotbohm** [comment]
Closing this due to the lack of feedback. You are welcome to reopen with additional information.

**Comment by megla-tlanghorst** [comment]
We also got this bug. We just created a new project with modulith and rabbit and it immediately cropped up.

It is reproducible with this: https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.5.5&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=devtools,configuration-processor,modulith,amqp

Just `./gradlew :bootRun` does the job. Maven should do the same as it's somewhere from the dependencies, but I don't know how that works then, but Initializr allows you to create a maven project as well.
